table RH_UtilidadMensual
	lineageTag: fc7332df-5d6d-43a9-aa7d-08a8aa0dc7e9

	column Periodo
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 73ebacd7-d8b0-4832-a82c-f1a556afd5d0
		summarizeBy: none
		sourceColumn: Periodo

		variation Variación
			isDefault
			relationship: b4e4a5ac-4e5c-46e3-8ccd-03489de659bc
			defaultHierarchy: LocalDateTable_b7a30c0e-6b95-4b65-abfe-9acc60b2abdf.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Utilidad
		dataType: double
		lineageTag: f320f355-8bef-4c9e-92fb-2e9a61c18853
		summarizeBy: sum
		sourceColumn: Utilidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Utilidad Bruta'
		dataType: double
		formatString: #,0.00
		lineageTag: f34a115b-12e8-448c-9419-4a44448f60e1
		summarizeBy: sum
		sourceColumn: Utilidad Bruta

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: int64
		formatString: 0
		lineageTag: c2d4889f-1340-44cd-9b20-411a7deba74a
		summarizeBy: sum
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	partition RH_UtilidadMensual-ce52970a-fb03-49fa-9824-3f5ab0824d0c = m
		mode: import
		source =
				let
				    Origen = SharePoint.Contents("https://finilagersa2014.sharepoint.com/sites/bw_bi/",[ApiVersion = 15]),
				    #"Documentos compartidos" = Origen{[Name="Documentos compartidos"]}[Content],
				    #"BI-BW" = #"Documentos compartidos"{[Name="BI-BW"]}[Content],
				    Maestros = #"BI-BW"{[Name="Maestros"]}[Content],
				    #"FijoVaribleKPI_EVALUACION xlsx" = Maestros{[Name="EvalPlanillas.xlsx"]}[Content],
				    #"Libro de Excel importado1" = Excel.Workbook(#"FijoVaribleKPI_EVALUACION xlsx"),
				    Utilidad_Sheet = #"Libro de Excel importado1"{[Item="UtilidadMensual",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Utilidad_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Periodo", type date}, {"Utilidad", Percentage.Type}, {"Utilidad Bruta", type number}}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Tipo cambiado",{{"Canal", Int64.Type}})
				in
				    #"Tipo cambiado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

