table VentasHistoricas
	excludeFromModelRefresh
	lineageTag: f65d2ede-3717-4602-ad15-4e449c4c3e7f

	column 'Canal distribución'
		dataType: int64
		formatString: 0
		lineageTag: aa4762b4-3580-453b-8e48-62e810292309
		summarizeBy: sum
		sourceColumn: Canal distribución

		annotation SummarizationSetBy = Automatic

	column 'Clase de factura'
		dataType: string
		lineageTag: a12eb9fc-fee2-48d0-9e9d-ad819f41fb6a
		summarizeBy: none
		sourceColumn: Clase de factura

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 232b4273-3b4f-4310-b5ac-e962bf20c071
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: b9ffcf75-bd5f-4e68-ad58-071911d7a87b
			defaultHierarchy: LocalDateTable_d540bd02-110a-4073-88e4-b0ae9bfb37f8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Factura
		dataType: string
		lineageTag: f0106a1a-5195-48b9-a8e9-78b988792ee9
		summarizeBy: none
		sourceColumn: Factura

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: int64
		formatString: 0
		lineageTag: c284484a-fcb3-450b-975d-42d3d6e1aa22
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column Sucursal
		dataType: string
		lineageTag: b92bc649-8cf5-4c84-84ad-71c60cb3feef
		summarizeBy: none
		sourceColumn: Sucursal

		annotation SummarizationSetBy = Automatic

	column Promoción
		dataType: string
		lineageTag: 86eb6fa0-546b-4e53-8b22-b50453a8e65c
		summarizeBy: none
		sourceColumn: Promoción

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: double
		lineageTag: c090c981-b242-48de-9f59-4eca44e26ca5
		summarizeBy: sum
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sector
		dataType: string
		lineageTag: 048fd488-691f-40b0-b021-abc60bf68f5e
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: int64
		formatString: 0
		lineageTag: 0cb23ced-9c31-4880-8db3-0eefc8cd512c
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Costo
		dataType: double
		lineageTag: a325abea-45ac-4335-8521-fc0a8d46f3ee
		summarizeBy: sum
		sourceColumn: Costo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Qty
		dataType: int64
		formatString: 0
		lineageTag: 556922a3-ca86-404d-953d-a400a8f3b4aa
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column Facturado
		dataType: double
		lineageTag: 1e0ebd3f-97fe-424e-a8e4-86f3b0edc9d7
		summarizeBy: sum
		sourceColumn: Facturado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Descuento
		dataType: double
		lineageTag: 8cbe8aad-1bc2-4861-8ecb-25e806c24976
		summarizeBy: sum
		sourceColumn: Descuento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DescuentoBruto
		dataType: double
		lineageTag: 1e8b863a-4ed3-4923-9ba7-34a3e299d298
		summarizeBy: sum
		sourceColumn: DescuentoBruto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Precio
		dataType: double
		lineageTag: 9ca027be-9ac1-4ab4-a2c7-887fa6e5e030
		summarizeBy: sum
		sourceColumn: Precio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Venta
		dataType: double
		lineageTag: 42f09a6e-5370-41f5-a36e-0d6139a0794c
		summarizeBy: sum
		sourceColumn: Venta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Centro
		dataType: string
		lineageTag: 240826eb-cf66-4eed-80a5-7f566b34a606
		summarizeBy: none
		sourceColumn: Centro

		annotation SummarizationSetBy = Automatic

	column División
		dataType: string
		lineageTag: 44efac22-66f0-4686-921f-f9241c3e017a
		summarizeBy: none
		sourceColumn: División

		annotation SummarizationSetBy = Automatic

	column Nit
		dataType: string
		lineageTag: f4012524-96f1-42c9-ba6e-ffb7b2407ace
		summarizeBy: none
		sourceColumn: Nit

		annotation SummarizationSetBy = Automatic

	partition VentasHistoricas = m
		mode: import
		source =
				let
				    Origen = Table.Combine({VentasSAP_2015, VentasSAP_2016, VentasSAP_2017, VentasSAP_2018, VentasSAP_2019, VentasSAP_2020, VentasSAP_2021, VentasSAP_2022, VentasSAP_2023, VentasSAP_2024, VentasSAP_2025}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Cliente", Int64.Type}, {"Canal distribución", Int64.Type}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado",100,106,Replacer.ReplaceValue,{"Vendedor"})
				in
				    #"Valor reemplazado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

